/*
 * Menu.java
 *
 * Created on 27 septembre 2004, 09:45
 */

package iut.dames.visudamier;

/**
 *
 * @author  samuel
 */
public class Menu extends javax.swing.JPanel {
    
    /** Creates new form Menu */
    public Menu() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        
        setLayout(new java.awt.BorderLayout());
        
    }//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
